### ISSUE TITLE
Text vs Audio?

### ISSUE THREAD

**Issue by machisuji** [Bunkerbewohner/video-games-by-language#1]
It would be nice if it allowed you to specifically search for games with the audio in the desired language. I've been looking for games in Chinese and all I found merely had (allegedly) Chinese text but no audio.

**Comment by Bunkerbewohner** [comment]
Good idea! Unfortunately GOG's API doesn't give that information. The website does, though. So I guess I'll need to crawl the individual HTML pages for games, too, to find out!

**Comment by Bunkerbewohner** [comment]
Fixed by https://github.com/Bunkerbewohner/video-games-by-language/commit/d99699c2c6f0b93209e2beb30c2488a43bca85d5
